/* create_brac_master_table.sql */

SELECT DiscardGeometryColumn("BRAC_MASTER", "geom");
DROP TABLE IF EXISTS "BRAC_MASTER";
CREATE TABLE "BRAC_MASTER"(
  "PK_UID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ID" INTEGER,
  "AREA" DOUBLE,
  "FAC_NAME" TEXT,
  "SBA_NAME" TEXT,
  "STATE" TEXT,
  "FAC_TYPE" TEXT,
  "CLOSURE" TEXT,
  "BRAC" TEXT,
  "BRANCH" TEXT,
  "STATE_FIPS" TEXT,
  "TBL_SHP_SOURCE" TEXT
);
SELECT AddGeometryColumn("BRAC_MASTER", "geom", 4019, "MULTIPOLYGON", "XY", 1);

SELECT DiscardGeometryColumn("BRAC_MASTER_WGS84", "geom");
DROP TABLE IF EXISTS "BRAC_MASTER_WGS84";
CREATE TABLE "BRAC_MASTER_WGS84"(
  "PK_UID" INTEGER PRIMARY KEY AUTOINCREMENT,
  "ID" INTEGER,
  "AREA" DOUBLE,
  "FAC_NAME" TEXT,
  "SBA_NAME" TEXT,
  "STATE" TEXT,
  "FAC_TYPE" TEXT,
  "CLOSURE" TEXT,
  "BRAC" TEXT,
  "BRANCH" TEXT,
  "STATE_FIPS" TEXT,
  "TBL_SHP_SOURCE" TEXT
);
SELECT AddGeometryColumn("BRAC_MASTER_WGS84", "geom", 4326, "MULTIPOLYGON", "XY", 1);
