/* insert_shp_data_into_brac_master.sql */

INSERT INTO BRAC_MASTER (ID, AREA, FAC_NAME, SBA_NAME, STATE, FAC_TYPE, CLOSURE, BRAC, BRANCH, STATE_FIPS, TBL_SHP_SOURCE, geom)
SELECT ID, AREA, FAC_NAME, SBA_NAME, ST_ABBR, FAC_TYPE, CLOSURE, BRAC, BRANCH, STFIPS, 'BRAC_12_30_15_SHP' AS TBL_SHP_SOURCE, geom
FROM BRAC_12_30_15_SHP;

INSERT INTO BRAC_MASTER (ID, AREA, FAC_NAME, STATE, FAC_TYPE, CLOSURE, BRAC, BRANCH, STATE_FIPS, TBL_SHP_SOURCE, geom)
SELECT ID, AREA, FAC_NAME, ST_ABBR, FAC_TYPE, CLOSURE, BRAC, BRANCH, STFIPS, 'BRAC_1_13_12_SHP' AS TBL_SHP_SOURCE, geom
FROM BRAC_1_13_12_SHP;

INSERT INTO BRAC_MASTER (ID, AREA, FAC_NAME, SBA_NAME, STATE, FAC_TYPE, CLOSURE, BRAC, BRANCH, STATE_FIPS, TBL_SHP_SOURCE, geom)
SELECT ID, AREA, FAC_NAME, SBA_NAME, ST_ABBR, FAC_TYPE, CLOSURE, BRAC, BRANCH, STFIPS, 'BRAC_1_16_14_SHP' AS TBL_SHP_SOURCE, geom
FROM BRAC_1_16_14_SHP;

INSERT INTO BRAC_MASTER (ID, AREA, FAC_NAME, STATE, FAC_TYPE, CLOSURE, BRAC, BRANCH, STATE_FIPS, TBL_SHP_SOURCE, geom)
SELECT ID, AREA, FAC_NAME, ST_ABBR, FAC_TYPE, CLOSURE, BRAC, BRANCH, STFIPS, 'BRAC_3_10_09_SHP' AS TBL_SHP_SOURCE, geom
FROM BRAC_3_10_09_SHP;

INSERT INTO BRAC_MASTER (ID, AREA, FAC_NAME, SBA_NAME, STATE, FAC_TYPE, CLOSURE, BRAC, BRANCH, STATE_FIPS, TBL_SHP_SOURCE, geom)
SELECT ID, AREA, FAC_NAME, SBA_NAME, ST_ABBR, FAC_TYPE, CLOSURE, BRAC, BRANCH, STFIPS, 'BRAC_3_30_15_SHP' AS TBL_SHP_SOURCE, geom
FROM BRAC_3_30_15_SHP;

INSERT INTO BRAC_MASTER (ID, AREA, FAC_NAME, STATE, FAC_TYPE, CLOSURE, BRAC, BRANCH, STATE_FIPS, TBL_SHP_SOURCE, geom)
SELECT ID, AREA, FAC_NAME, ST_ABBR, FAC_TYPE, CLOSURE, BRAC, BRANCH, STFIPS, 'BRAC_4_3_09_SHP' AS TBL_SHP_SOURCE, geom
FROM BRAC_4_3_09_SHP;

INSERT INTO BRAC_MASTER (ID, AREA, FAC_NAME, STATE, FAC_TYPE, CLOSURE, BRAC, STATE_FIPS, TBL_SHP_SOURCE, geom)
SELECT  ID, AREA, NAME, STATE, TYPE, CLOSURE, BRAC, STATEFIPS, 'BRAC_5_11_06_SHP' AS TBL_SHP_SOURCE, geom
FROM BRAC_5_11_06_SHP;

INSERT INTO BRAC_MASTER (ID, AREA, FAC_NAME, SBA_NAME, STATE, FAC_TYPE, CLOSURE, BRAC, BRANCH, STATE_FIPS, TBL_SHP_SOURCE, geom)
SELECT ID, AREA, FAC_NAME, SBA_NAME, ST_ABBR, FAC_TYPE, CLOSURE, BRAC, BRANCH, STFIPS, 'BRAC_6_13_13_SHP' AS TBL_SHP_SOURCE, geom
FROM BRAC_6_13_13_SHP;

INSERT INTO BRAC_MASTER (ID, AREA, FAC_NAME, SBA_NAME, STATE, FAC_TYPE, CLOSURE, BRAC, BRANCH, STATE_FIPS, TBL_SHP_SOURCE, geom)
SELECT ID, AREA, FAC_NAME, SBA_NAME, ST_ABBR, FAC_TYPE, CLOSURE, BRAC, BRANCH, STFIPS, 'BRAC_8_12_14_SHP' AS TBL_SHP_SOURCE, geom
FROM BRAC_8_12_14_SHP;

INSERT INTO BRAC_MASTER (ID, AREA, FAC_NAME, STATE, FAC_TYPE, CLOSURE, BRAC, BRANCH, STATE_FIPS, TBL_SHP_SOURCE, geom)
SELECT ID, AREA, FAC_NAME, ST_ABBR, FAC_TYPE, CLOSURE, BRAC, BRANCH, STFIPS, 'BRAC_11_6_12_SHP' AS TBL_SHP_SOURCE, geom
FROM BRAC_11_6_12_SHP;

INSERT INTO BRAC_MASTER (ID, AREA, FAC_NAME, STATE, FAC_TYPE, CLOSURE, BRAC, BRANCH, STATE_FIPS, TBL_SHP_SOURCE, geom)
SELECT ID, AREA, FAC_NAME, ST_ABBR, FAC_TYPE, CLOSURE, BRAC, BRANCH, STFIPS, 'BRAC_11_30_12_SHP' AS TBL_SHP_SOURCE, geom
FROM BRAC_11_30_12_SHP;
