/* reproject_brac_master_table.sql */

INSERT INTO BRAC_MASTER_WGS84 (PK_UID, ID, AREA, FAC_NAME, SBA_NAME, STATE, FAC_TYPE, CLOSURE, BRAC, BRANCH, STATE_FIPS, TBL_SHP_SOURCE, geom)
SELECT PK_UID, ID, AREA, FAC_NAME, SBA_NAME, STATE, FAC_TYPE, CLOSURE, BRAC, BRANCH, STATE_FIPS, TBL_SHP_SOURCE, ST_Transform(geom, 4326)
FROM BRAC_MASTER;
